config/routes.rb
Rails.application.routes.draw do
  resources :topics do
    resources :questions, except: [:index]
  end

  resources :questions, only: [:index] do
    resources :answers, only: [:create, :destroy]
  end


  get 'users/show'

  # devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  authenticated :user do
    root 'topics#index', as: :authenticated_root
  end

  get 'about' => 'welcome#about'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :body, length: { minimum: 5 }, presence: true
  validates :user, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :votes, dependent: :destroy

  default_scope { order('created_at DESC') }

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 10 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :questions, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :votes, dependent: :destroy

  before_save { self.role ||= :member }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates :username,
    :presence => true,
    :uniqueness => {
      :case_sensitive => false
    }

  enum role: [:member, :admin]
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_user, only: [:destroy]

  def create
    @question = Question.find(params[:question_id])
    answer = @question.answers.new(answer_params)
    answer.user = current_user

    if answer.save
      flash[:notice] = "Answer saved successfully."
      redirect_to [@question.topic, @question]
    else
      flash[:alert] = "Answer failed to save."
      redirect_to [@question.topic, @question]
    end
  end

  def destroy
    @question = Question.find(params[:question_id])
    answer = Answer.find(params[:id])

    if answer.destroy
      flash[:notice] = "Answer was deleted successfully."
      redirect_to [@question.topic, @question]
    else
      flash[:alert] = "Answer couldn't be deleted. Try again."
      redirect_to [@question.topic, @question]
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def authorize_user
    answer = Answer.find(params[:id])
    unless current_user == answer.user || current_user.admin?
      flash[:alert] = "You do not have permission to delete this answer."
      redirect_to [answer.question.topic, answer.question]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/concerns/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"]

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user, except: [:index, :show, :new, :create]

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @question = Question.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @question = @topic.questions.build(question_params)
    @question.user = current_user

    if @question.save
      flash[:notice] = "Question was saved successfully."
      redirect_to [@topic, @question]
    else
      flash.now[:alert] = "There was an error saving the question. Please try again."
      redirect_to :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.assign_attributes(question_params)

    if @question.save
      flash[:notice] = "Question was updated successfully."
      redirect_to [@question.topic, @question]
    else
      flash.now[:alert] = "There was an error updating the question. Please try again."
      redirect_to :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])

    if @question.destroy
      flash[:notice] = "\"#{@question.title}\" was deleted successfully."
      redirect_to @question.topic
    else
      flash.now[:alert] = "There was an error deleting the question."
      render :show
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def authorize_user
    question = Question.find(params[:id])

    unless current_user == question.user || current_user.admin?
      flash[:alert] = "You must be an admin to do that."
      redirect_to [question.topic, question]
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user, except: [:index, :show]

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      flash[:notice] = "Topic was saved successfully."
      redirect_to @topic
    else
      flash.now[:alert] = "Error creating topic. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    @topic.assign_attributes(topic_params)

    if @topic.save
      flash[:notice] = "Topic was updated successfully."
      redirect_to @topic
    else
      flash.now[:alert] = "Error saving topic. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])

    if @topic.destroy
      flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
      redirect_to action: :index
    else
      flash.now[:alert] = "Error deleting topic. Please try again."
      render :show
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:name, :description, :public)
  end

  def authorize_user
    unless current_user.admin?
      flash[:alert] = "You must be an admin to perform the action."
      redirect_to topics_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, except: [:index, :about]

  def index
  end

  def about
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
  def user_is_authorized_for_answer?(answer)
    current_user && (current_user == answer.user || current_user.admin?)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
   def user_is_authorized_for_question?(question)
        current_user && (current_user == question.user || current_user.admin?)
   end
 end

app/helpers/topics_helper.rb
module TopicsHelper
  def user_is_authorized_for_topics?
    current_user && current_user.admin?
  end
end

app/views/answers/_answer.html.erb
<div class="media">
  <div class="media-body">
    <small>
      <%= answer.user.username %> posted <%= time_ago_in_words(answer.created_at) %> ago

      <% if user_is_authorized_for_answer?(answer) %>
        | <% link_to "Delete", [@question, answer], method: :delete %>
      <% end %>
    </small>
    <p><%= answer.body %></p>
  </div>
</div>

app/views/answers/_form.html.erb
<h5>- Add an answer -</h5>
 <%= form_for [question, answer] do |f| %>
   <div class="form-group">
     <%= f.label :body, class: 'sr-only' %>

     <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter an answer here" %>

   </div>
   <%= f.submit "Submit Comment", class: 'btn btn-default pull-right' %>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Konnichiwa</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Topics", topics_path %></li>
      <li><%= link_to "Questions", questions_path %></li>
      <li><%= link_to "About", about_path %></li>

      <div class="pull-right user-info">
        <% if user_signed_in? %>
          Signed in as: <strong><%= link_to current_user.username, users_show_path(current_user) %></strong> |
          <%= link_to "Edit profile", edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> -
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
        <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash.now[:alert] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash.now[:alert] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>



  <%= yield %>
  </div>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_for [topic, question] do |f| %>
   <div class="form-group">
     <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
   </div>
   <div class="form-group">
     <%= f.label :body %>
     <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
   </div>
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
 <% end %>

app/views/questions/edit.html.erb
<div class="questions">
  <h2>Edit Question</h2>

  <div class="row">
    <div class="col-md-4">
      <p>Guidelines for questions</p>
      <ul>
        <li>Ask about one phrase.</li>
        <li>Add some context if you think you need to.</li>
        <li>There is no stupid question!</li>
      </ul>
    </div>
    <div class="col-md-8">
      <%= render partial: 'form', locals: { topic: @question.topic, question: @question } %>
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<div class="questions">
  <h3>All Questions</h3>
    <% @questions.each do |question| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <p><%= link_to question.title, topic_question_path(question.topic, question) %></p>
            <small>
              submitted <%= time_ago_in_words(question.created_at) %> ago by <%= question.user.username %>
            </small>
          </h4>
        </div>
      </div>
    <% end %>
  </h2>
</div>

app/views/questions/new.html.erb
<div class="questions">
  <h2>New Question</h2>

  <div class="row">
    <div class="col-md-4">
      <p>Guidelines for questions</p>
      <ul>
        <li>Ask about one phrase.</li>
        <li>Add some context if you think you need to.</li>
        <li>There is no stupid question!</li>
      </ul>
    </div>
    <div class="col-md-8">
        <%= render partial: 'form', locals: { topic: @topic, question: @question } %>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<div class="questions">
  <h3>
    <%= @question.title %> </br>
    <small>
      submitted <%= time_ago_in_words(@question.created_at) %> ago by <%= @question.user.username %>
    </small>
  </h3>
  <div class="row">
    <div class="col-md-8">
      <p class="question-body"><%= @question.body %></p>

      <div>
        <h4>- Answers- </h4>
        <%= render @question.answers  %>
      </div>
      <% if current_user %>
        <%= render 'answers/form', answer: Answer.new, question: @question %>
      <% end %>
      </br>
      </br>
      <%= link_to "Go to the Topic", topic_path(@question.topic) %>
    </div>

    <% if user_is_authorized_for_question?(@question) %>
      <div class="col-md-4">
        <%= link_to "Edit", edit_topic_question_path(@question.topic, @question), class: 'btn btn-success' %>
        <%= link_to "Delete Question", [@question.topic, @question], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this question?'} %>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/edit.html.erb
<h2>Edit Topic</h2>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for topics:</p>
     <ul>
       <li>Make sure the topic is appropriate.</li>
       <li>Make is easy to understand.</li>
       <li>Smile when you type.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @topic do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
       </div>
       <div class="form-group">
         <%= f.label :description %>
         <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
       </div>
       <div class="form-group">
         <%= f.label :public, class: 'checkbox' do %>
           <%= f.check_box :public %> Public topic
         <% end %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/topics/index.html.erb
<h2>Topics</h2>

 <div class="row">
   <div class="col-md-8">
     <% @topics.each do |topic| %>
       <div class="media">
         <div class="media-body">
           <h4 class="media-heading">
             <%= link_to topic.name, topic %>
           </h4>
           <small>
             <%= topic.description %>
           </small>
         </div>
       </div>
     <% end %>
   </div>

   <% if user_is_authorized_for_topics? %>
     <div class="col-md-4">
       <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
     </div>
   <% end %>
 </div>

app/views/topics/new.html.erb
<h2>New Topic</h2>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for topics:</p>
     <ul>
       <li>Make sure the topic is appropriate.</li>
       <li>Make is easy to understand.</li>
       <li>Smile when you type.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @topic do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
       </div>
       <div class="form-group">
         <%= f.label :description %>
         <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
       </div>
       <div class="form-group">
         <%= f.label :public, class: 'checkbox' do %>
           <%= f.check_box :public %> Public topic
         <% end %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/topics/show.html.erb
<h2><%= @topic.name %></h2>

 <% if user_is_authorized_for_topics? %>
   <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
   <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>
 <% end %>

   <div class="col-md-8">
     <p class="lead"><%= @topic.description %></p>

     <% @topic.questions.each do |question| %>
       <div class="media">
         <div class="media-body">
           <h4 class="media-heading">
             <%= link_to question.title, topic_question_path(@topic, question) %>
           </h4>

           <small>
             submitted <%= time_ago_in_words(question.created_at) %> ago by <%= question.user.username %><br>
             <%= question.answers.count %> Answers
           </small>

         </div>
       </div>
     <% end %>
   </div>
   <div class="col-md-8", id="new-question">
     <%= link_to "New Question", new_topic_question_path(@topic), class: 'btn btn-success' %>
   </div>
 </div>

app/views/users/show.html.erb
<div class="user-show">
  <h4>Username: <%= @user.username %></h4>
  <div class="row">
    <div class="col-md-8">
      <p><strong>Email: </strong><%= @user.email %></p>
      <p><strong>member since: </strong><%= @user.created_at.to_date %></p>
    </div>
  </div>
</div>

app/views/welcome/about.html.erb
<div class="welcome">
  <h1>About</h1>

  <h4>Konnichiwa is a free educational social media application, created by me - Emiko Dodson. I am from Japan and enjoy helping anyone studying Japanese.
  I wanted to create a fun and safe space for anyone who is interested in, or studying Japanese language / culture to get connected with Japanese users, and get help from them.
  There is no question too small to ask here. Don't be shy and ask away!</h4>
</div>

app/views/welcome/index.html.erb
<div class="welcome">
  <h1>Konnichiwa!</h1>
  <h4>Learning a foreign language means more than just adding some new knowledge. You will learn a new culture. You will meet new people. The way you look at the world will change.
  <%= link_to "Join us", new_user_registration_path %> and start your journey today.</h4>
</div>